// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Dish is the golang structure for table dish.
type Dish struct {
	Id          int64       `json:"id"          description:"主键"`
	Name        string      `json:"name"        description:"菜品名称"`
	Price       float64     `json:"price"       description:"菜品价格"`
	Description string      `json:"description" description:"描述信息"`
	Status      int         `json:"status"      description:"0 停售 1 起售"`
	CreateTime  *gtime.Time `json:"create_time" description:"创建时间"`
	UpdateTime  *gtime.Time `json:"update_time" description:"更新时间"`
	CreateUser  int64       `json:"create_user" description:"创建人"`
	UpdateUser  int64       `json:"update_user" description:"修改人"`
}