// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Employee is the golang structure for table employee.
type Employee struct {
	Id         int64       `json:"id"          description:"主键"`
	Name       string      `json:"name"        description:"姓名"`
	Username   string      `json:"username"    description:"用户名"`
	Password   string      `json:"password"    description:"密码"`
	Email      string      `json:"email"       description:"邮箱"`
	Phone      string      `json:"phone"       description:"手机号"`
	CreateTime *gtime.Time `json:"create_time" description:"创建时间"`
}