// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Order is the golang structure for table orders.
type Order struct {
	Id           int64       `json:"id"            description:"主键"`
	Number       string      `json:"number"        description:"订单号"`
	Status       int         `json:"status"        description:"订单状态 1待付款 2待接单 3已接单 4已完成 5已取消 6退款"`
	UserId       int64       `json:"user_id"       description:"下单用户"`
	OrderTime    *gtime.Time `json:"order_time"    description:"下单时间"`
	CheckoutTime *gtime.Time `json:"checkout_time" description:"结账时间"`
	PayMethod    int         `json:"pay_method"    description:"支付方式 1微信,2支付宝"`
	PayStatus    int8        `json:"pay_status"    description:"支付状态 0未支付 1已支付 2退款"`
	Amount       float64     `json:"amount"        description:"实收金额"`
	Remark       string      `json:"remark"        description:"备注"`
	Phone        string      `json:"phone"         description:"手机号"`
	UserName     string      `json:"user_name"     description:"用户名称"`
	CancelReason string      `json:"cancel_reason" description:"订单取消原因"`
	CancelTime   *gtime.Time `json:"cancel_time"   description:"订单取消时间"`
}