// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// OrderDetail is the golang structure for table order_detail.
type OrderDetail struct {
	Id      int64   `json:"id"       description:"主键"`
	Name    string  `json:"name"     description:"名字"`
	OrderId int64   `json:"order_id" description:"订单id"`
	DishId  int64   `json:"dish_id"  description:"菜品id"`
	Number  int     `json:"number"   description:"数量"`
	Amount  float64 `json:"amount"   description:"金额"`
}